### ISSUE TITLE
Caimanの環境構築時にいつまでたっても終わらない問題を確認

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#422]
## 概要
Caimanのワークフローを実行するといつまでも処理が終わらない。
同環境でCaimanを手動でconda installしても終わらないので、おそらく環境構築で止まっていると思われる。

![image (4)](https://user-images.githubusercontent.com/45911784/225531956-c3a0f544-47c7-4745-8e29-f94a9c3d2699.png)

## 環境
Ubuntu 18.04

## 関連
- #446

**Comment by emuemuJP** [comment]
いただいたいくつかのエラー事例

5. Mac Catalina  Data->CaImAn(caimanmc)  error 
`
File "/Users/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/7bfe9fc43e104333baf3fb3fb525a6bb_/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: dlopen(/Users/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/7bfe9fc43e104333baf3fb3fb525a6bb_/lib/python3.8/site-packages/cv2/python-3.8/cv2.cpython-38-darwin.so, 2): Library not loaded: @rpath/libgstreamer-1.0.0.dylib Referenced from: /Users/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/7bfe9fc43e104333baf3fb3fb525a6bb_/lib/libopencv_gapi.4.6.0.dylib Reason: Incompatible library version: libopencv_gapi.406.dylib requires version 1401.0.0 or later, but libgstreamer-1.0.0.dylib provides version 0.0.0
`

6. Linux Ubuntu 22.04 LTS    Data->CaImAn(caimanmc) error
`
Building DAG of jobs...
Removing incomplete Conda environment optinist/conda/caiman_env.yaml...
Creating conda environment optinist/conda/caiman_env.yaml...
Downloading and installing remote packages.
INFO:     127.0.0.1:58608 - "POST /run/result/93f70455 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58608 - "POST /run/result/93f70455 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58608 - "POST /run/result/93f70455 HTTP/1.1" 200 OK

2023-04-12 09:25:04,005 : ERROR - logger.py - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 590, in create\n out = create_env(env_file, filetype="yaml")\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 552, in create_env\n out = shell.check_output(\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/shell.py", line 63, in check_output\n return sp.check_output(cmd, shell=True, executable=executable, **kwargs)\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/subprocess.py", line 415, in check_output\n return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/subprocess.py", line 516, in run\n raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'conda env create --quiet --file "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_.yaml" --prefix "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_"\' died with <Signals.SIGKILL: 9>.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/__init__.py", line 757, in snakemake\n success = workflow.execute(\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/workflow.py", line 930, in execute\n dag.create_conda_envs(\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/dag.py", line 351, in create_conda_envs\n env.create(dryrun)\n File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 609, in create\n raise CreateCondaEnvironmentException(\nsnakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from /home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/optinist/conda/caiman_env.yaml:\nCommand:\nconda env create --quiet --file "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_.yaml" --prefix "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_"\nOutput:\nCollecting package metadata (repodata.json): ...working... done\nSolving environment: ...working... \n', 'timestamp': 1681259104.002604}
`

7. Windows10 Enterprise  wsl2 Data->CaImAn(caimanmc) エラー　(install, suite2p, lccdは問題ないです）
`
File "/home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/.snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: libGL.so.1: cannot open shared object file: No such file or directory
`
以下　log です。
INFO:     127.0.0.1:46030 - "POST /run HTTP/1.1" 200 OK
Building DAG of jobs...
Creating conda environment optinist/conda/caiman_env.yaml...
Downloading and installing remote packages.
INFO:     127.0.0.1:46044 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46044 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
...
INFO:     127.0.0.1:46074 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46076 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46076 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
Environment for /home/yukako/anaconda3/envs/optinist/lib/python3.8/site-packages/optinist/conda/caiman_env.yaml created (location: .snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_)
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
2            1              1              1
3            1              1              1
all          1              1              1
total        3              1              1

Select jobs to execute...

[Thu Apr 13 09:25:57 2023]
rule 3:
    input: /tmp/optinist/input/data_endoscope.tif
    output: /tmp/optinist/output/92efaba1/input_0/data_endoscope.pkl
    jobid: 2
    reason: Missing output files: /tmp/optinist/output/92efaba1/input_0/data_endoscope.pkl
    resources: tmpdir=/tmp

[Thu Apr 13 09:25:59 2023]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Thu Apr 13 09:25:59 2023]
rule 2:
    input: /tmp/optinist/output/92efaba1/input_0/data_endoscope.pkl
    output: /tmp/optinist/output/92efaba1/caiman_mc_7pg5i3xogr/caiman_mc.pkl
    jobid: 1
    reason: Missing output files: /tmp/optinist/output/92efaba1/caiman_mc_7pg5i3xogr/caiman_mc.pkl; Input files updated by another job: /tmp/optinist/output/92efaba1/input_0/data_endoscope.pkl
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_
Activating conda environment: .snakemake/conda/2a94d6b7487b12164e741c55edbb89b5_
INFO:     127.0.0.1:46076 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK
[Thu Apr 13 09:26:04 2023]
Finished job 1.
2 of 3 steps (67%) done
Select jobs to execute...

[Thu Apr 13 09:26:04 2023]
localrule all:
    input: /tmp/optinist/output/92efaba1/caiman_mc_7pg5i3xogr/caiman_mc.pkl
    jobid: 0
    reason: Input files updated by another job: /tmp/optinist/output/92efaba1/caiman_mc_7pg5i3xogr/caiman_mc.pkl
    resources: tmpdir=/tmp

[Thu Apr 13 09:26:04 2023]
Finished job 0.
3 of 3 steps (100%) done
Complete log: .snakemake/log/2023-04-13T092021.076519.snakemake.log
INFO:     127.0.0.1:46076 - "POST /run/result/92efaba1 HTTP/1.1" 200 OK


8. Windows10 Enterprise  powershell Data->CaImAn(caimanmc) エラー　(install, suite2p, lccdは問題ないです）
`
2023-04-13 08:20:25,578 : ERROR - logger.py - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\deployment\\conda.py", line 590, in create\n out = create_env(env_file, filetype="yaml")\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\deployment\\conda.py", line 552, in create_env\n out = shell.check_output(\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\shell.py", line 63, in check_output\n return sp.check_output(cmd, shell=True, executable=executable, **kwargs)\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\subprocess.py", line 415, in check_output\n return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\subprocess.py", line 516, in run\n raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'conda env create --quiet --file "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\.snakemake\\conda\\913dcc436b0a7b98dcc3080d8722c1d4_.yaml" --prefix "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\.snakemake\\conda\\913dcc436b0a7b98dcc3080d8722c1d4_"\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\__init__.py", line 757, in snakemake\n success = workflow.execute(\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\workflow.py", line 930, in execute\n dag.create_conda_envs(\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\dag.py", line 351, in create_conda_envs\n env.create(dryrun)\n File "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\snakemake\\deployment\\conda.py", line 609, in create\n raise CreateCondaEnvironmentException(\nsnakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\optinist/conda/caiman_env.yaml:\nCommand:\nconda env create --quiet --file "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\.snakemake\\conda\\913dcc436b0a7b98dcc3080d8722c1d4_.yaml" --prefix "C:\\Users\\yukako\\anaconda3\\envs\\optinist\\lib\\site-packages\\.snakemake\\conda\\913dcc436b0a7b98dcc3080d8722c1d4_"\nOutput:\nCollecting package metadata (repodata.json): ...working... done\nSolving environment: ...working... done\nPreparing transaction: ...working... done\nVerifying transaction: ...working... done\nExecuting transaction: ...working... \n\n Windows 64-bit packages of scikit-learn can be accelerated using scikit-learn-intelex.\n More details are available here: https://intel.github.io/scikit-learn-intelex\n\n For example:\n\n $ conda install scikit-learn-intelex\n $ python -m sklearnex my_application.py\n\n\ndone\nERROR conda.core.link:_execute(745): An error occurred while installing package \'defaults::tensorflow-estimator-2.9.0-py38haa95532_0\'.\nRolling back transaction: ...working... done\n\n[Errno 2] No such file or directory: \'C:\\\\Users\\\\yukako\\\\anaconda3\\\\envs\\\\optinist\\\\lib\\\\site-packages\\\\.snakemake\\\\conda\\\\913dcc436b0a7b98dcc3080d8722c1d4_\\\\Lib\\\\site-packages\\\\tensorflow_estimator\\\\python\\\\estimator\\\\canned\\\\linear_optimizer\\\\python\\\\utils\\\\__pycache__\\\\sharded_mutable_dense_hashtable.cpython-38.pyc\'\n()\n\n\n', 'timestamp': 1681341625.5783498}
`

**Comment by itutu-tienday** [comment]
以下関連チケットでの検証や改善で、その後 再発は確認されていないため、クローズする。（再発があれば再検証する）

- #446
