### ISSUE TITLE
サイズが大きいInputの際のOverflowError

### ISSUE THREAD

**Issue by ReiHashimoto** [oist/optinist#540]
Dataclassのsave_jsonメソッドで、`np.save`の際に発生する

```
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol
4 or higher
```

numpy.saveから呼び出される`pickle.dump(array, fp, protocol=3, **pickle_kwargs)`で、protocolを4以上にする必要がある

numpy.saveではパラメータを編集できないようなので、同等のメソッドを作成？
対応方針要調査。

**Comment by emuemuJP** [comment]
同様のワークフロー実行時に別のエラーが発生

` in _error_on_new_warn_on_construct raise ValueError(error_msg) ValueError: ImageSeries 'corrected': Format must be 'external' when external_file is specified.`

<img width="1460" alt="スクリーンショット 2023-07-07 16 21 17" src="https://github.com/oist/optinist/assets/49627335/20a39110-2349-4f23-bb81-3e41a99bdc2e">

**Comment by ReiHashimoto** [comment]
さらに別のエラーパターン

こちらはcaiman_mcまでは成功

![Screenshot 2023-07-07 at 17 12 39](https://github.com/oist/optinist/assets/42664619/3622973a-0426-43f6-8cf2-f9e34ea9f530)

![Screenshot 2023-07-07 at 17 10 47](https://github.com/oist/optinist/assets/42664619/53912019-a57f-425c-b200-937e0cc02574)

```
2023-07-07 17:07:48,782 : ERROR - logger.py - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
  run(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/optinist/Snakefile", line 94, in __rule_4
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 1567, in script
  executor.evaluate()
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 462, in evaluate
  self.execute_script(fd.name, edit=edit)
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 683, in execute_script
  self._execute_cmd(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 493, in _execute_cmd
  return shell(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/shell.py", line 300, in __new__
  raise sp.CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'source /Users/rei_hashimoto/anaconda3/bin/activate \'/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/.snakemake/conda/3abd0cc9bc7ca3d1a0991ab5273621c1_\'; set -euo pipefail;  python /Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/.snakemake/scripts/tmp_0noz5l5.func.py\' returned non-zero exit status 137.\n', 'timestamp': 1688717268.780235}

```

**Comment by ReiHashimoto** [comment]
work on fork.
- https://github.com/arayabrain/barebone-studio/issues/164
